
###
// consulta todo los datos
GET  http://localhost:3000/api/tasks

###
//crea un documento en la bd
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    //"title": "Hacer un sitio web en vue",
    "description": "FREElance",
    "done": true
}

###
//consulta un elemento por ID de mongoDB
GET http://localhost:3000/api/tasks/6279c2aa940e286be4298e6d


###
// elimina documento por ID
DELETE http://localhost:3000/api/tasks/6279f5f0902e7105e7daa8e0

###
// consulta los datos que tiene la propiedad done en true
GET http://localhost:3000/api/tasks/done

###
// modifica el campo seleccionado
PUT http://localhost:3000/api/tasks/6278c55de90fd1a8002d939f
Content-Type: application/json

{
    "description": " este en un ejemplo"
}

###
// busqueda con paginacion
GET http://localhost:3000/api/tasks?size=4&page=1

###
//buscar por titulo
GET http://localhost:3000/api/tasks?size=4&page=0&title=react