
###
// consulta todo los datos
GET  http://localhost:3000/api/tasks

###
//crea un documento en la bd
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
   "nombre" : "hola mundo",
   "estado" : "true"
}

###
//consulta un elemento por ID de mongoDB
GET http://localhost:3000/api/tasks/627b438254f63e983c250e62


###
// elimina documento por ID
DELETE http://localhost:3000/api/tasks/627b45b01cdf6dfa3618c049

###
// consulta los datos que tiene la propiedad done en true
GET http://localhost:3000/api/tasks/done

###
// modifica el campo seleccionado
PUT http://localhost:3000/api/tasks/627b4868158b5c78899ee1c1
Content-Type: application/json

{
    "nombre": " modificado"
}

###
// busqueda con paginacion
GET http://localhost:3000/api/tasks?size=4&page=4

###
//buscar por titulo
GET http://localhost:3000/api/tasks?size=4&page=0&nombre=estesi